"""create schedules table

Revision ID: 8feb86b963ca
Revises: b9cabae99fca
Create Date: 2026-07-16 23:08:36.605749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8feb86b963ca"
down_revision: Union[str, Sequence[str], None] = "b9cabae99fca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("medicine_name", sa.String(length=255), nullable=False),
        sa.Column(
            "frequency",
            sa.Integer(),
            nullable=False,
            comment="Количество приемов в день",
        ),
        sa.Column(
            "treatment_days",
            sa.Integer(),
            nullable=True,
            comment="None - постоянный прием",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedules_user_id"), "schedules", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedules_user_id"), table_name="schedules")
    op.drop_table("schedules")
    # ### end Alembic commands ###
